version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: provider
    main: ./cmd/provider
    binary: nomos-provider-file
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}

archives:
  - id: default
    name_template: 'nomos-provider-file-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: autonomous-bits
    name: nomos-provider-file
  draft: false
  prerelease: auto
  name_template: "Release v{{ .Version }}"
  header: |
    ## Nomos File Provider v{{ .Version }}
    
    This release provides prebuilt binaries for the Nomos file provider.
    
    Each archive includes:
    - The `nomos-provider-file` executable
    - `LICENSE` file
    - `README.md` documentation
    - `CHANGELOG.md` release notes
    
    ### Installation
    
    Download the appropriate archive for your platform and verify the checksum:
    
    **Linux/macOS:**
    ```bash
    # Download archive
    curl -LO https://github.com/autonomous-bits/nomos-provider-file/releases/download/v{{ .Version }}/nomos-provider-file-{{ .Version }}-<os>-<arch>.tar.gz
    
    # Verify checksum
    curl -LO https://github.com/autonomous-bits/nomos-provider-file/releases/download/v{{ .Version }}/SHA256SUMS
    shasum -a 256 -c SHA256SUMS
    
    # Extract
    tar -xzf nomos-provider-file-{{ .Version }}-<os>-<arch>.tar.gz
    
    # Install
    chmod +x nomos-provider-file
    sudo mv nomos-provider-file /usr/local/bin/
    ```
    
    **Windows:**
    ```powershell
    # Download archive
    curl -LO https://github.com/autonomous-bits/nomos-provider-file/releases/download/v{{ .Version }}/nomos-provider-file-{{ .Version }}-windows-<arch>.tar.gz
    
    # Extract (requires tar, available in Windows 10+ or Git Bash)
    tar -xzf nomos-provider-file-{{ .Version }}-windows-<arch>.tar.gz
    
    # Move to PATH directory as needed
    ```
    
    ### Changes
  footer: |
    **Full Changelog**: https://github.com/autonomous-bits/nomos-provider-file/compare/{{ .PreviousTag }}...{{ .Tag }}
